version: "3"
services:
  telega-back:
    image: telega-back:latest5
    build:
      context: .
      dockerfile: ./Dockerfile
      target: telega-back
    container_name: telega-back
    #restart: always
    ports:
      - 5003:5003
      - 5002:5002
    env_file:
      - ./apps/telega-back/.env.prod
    depends_on:
      - postgres

  api-gateway:
    image: api-gateway:latest2
    build:
      context: .
      dockerfile: ./Dockerfile
      target: api-gateway
    container_name: api-gateway
    ports:
      - 4000:4000
    env_file: ./apps/api-gateway/.env.prod

  admin-back:
    image: admin-back:latest1
    build:
      context: .
      dockerfile: ./Dockerfile
      target: admin-back
    container_name: admin-back
    ports:
      - 5001:5001
    env_file: ./apps/admin-back/.env.prod

  admin-front:
    image: admin-front:latest8
    build:
      context: .
      dockerfile: ./apps/admin-front/Dockerfile
      target: admin-front
    container_name: admin-front
    ports:
      - 3000:3000
    env_file: ./apps/admin-front/.env.prod

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: crypto-telega
      POSTGRES_USER: daria
      POSTGRES_PASSWORD: 12345
      POSTGRES_PORT: 5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
