version: "3"
services:
  telega-back:
    image: telega-back:init2
    build:
      context: .
      dockerfile: ./apps/telega-back/Dockerfile
    container_name: telega-back
    #restart: always
    ports:
      - 5003:5003
      - 5002:5002
    volumes:
      - ./apps/telega-back/.env.prod:/usr/src/app
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: crypto-telega
      POSTGRES_USER: daria
      POSTGRES_PASSWORD: 12345
      POSTGRES_PORT: 5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
