import { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import '@/styles/globals.css';

const inter = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Наш проект',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru">
      <head></head>
      <body>{children}</body>
    </html>
  );
}
