/**
 * This file is auto-generated by nestjs-proto-gen-ts
 */
// https://github.com/AlexDaSoul/nestjs-proto-gen-ts
import { Observable } from "rxjs";
import { Metadata } from "@grpc/grpc-js";

export namespace auth {
  export interface AuthService {
    login(
      data: LoginRequest,
      metadata?: Metadata,
      ...rest: any[]
    ): Observable<LoginResponse>;
  }
  export interface LoginRequest {
    password?: string;
    email?: string;
  }
  export interface LoginResponse {
    token?: string;
  }
}
